-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.32-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for realestatephp
CREATE DATABASE IF NOT EXISTS `realestatephp` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `realestatephp`;

-- Dumping structure for table realestatephp.about
CREATE TABLE IF NOT EXISTS `about` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `content` longtext NOT NULL,
  `image` varchar(300) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table realestatephp.about: ~1 rows (approximately)
REPLACE INTO `about` (`id`, `title`, `content`, `image`) VALUES
	(11, 'test', '<p>lorem ipsum</p>', 'gold.png');

-- Dumping structure for table realestatephp.admin
CREATE TABLE IF NOT EXISTS `admin` (
  `aid` int(10) NOT NULL AUTO_INCREMENT,
  `auser` varchar(50) NOT NULL,
  `aemail` varchar(50) NOT NULL,
  `apass` varchar(50) NOT NULL,
  `adob` date NOT NULL,
  `aphone` varchar(15) NOT NULL,
  PRIMARY KEY (`aid`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table realestatephp.admin: ~1 rows (approximately)
REPLACE INTO `admin` (`aid`, `auser`, `aemail`, `apass`, `adob`, `aphone`) VALUES
	(2, 'admin', 'admin@gmail.com', 'd033e22ae348aeb5660fc2140aec35850c4da997', '2024-12-08', '1234');

-- Dumping structure for table realestatephp.city
CREATE TABLE IF NOT EXISTS `city` (
  `cid` int(50) NOT NULL AUTO_INCREMENT,
  `cname` varchar(100) NOT NULL,
  `sid` int(50) NOT NULL,
  PRIMARY KEY (`cid`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table realestatephp.city: ~5 rows (approximately)
REPLACE INTO `city` (`cid`, `cname`, `sid`) VALUES
	(14, 'Metro Manila', 23),
	(15, 'Quezon City', 23),
	(16, 'Davao City', 23),
	(17, 'Caloocan ', 23),
	(18, 'Cebu', 23);

-- Dumping structure for table realestatephp.contact
CREATE TABLE IF NOT EXISTS `contact` (
  `cid` int(50) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `subject` varchar(100) NOT NULL,
  `message` varchar(250) NOT NULL,
  PRIMARY KEY (`cid`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table realestatephp.contact: ~3 rows (approximately)
REPLACE INTO `contact` (`cid`, `name`, `email`, `phone`, `subject`, `message`) VALUES
	(8, 'testagent', 'testagent@gmail.com', '123213213', 'test', 'test '),
	(9, 'testagent', 'testagent@gmail.com', '123213213', 'test', 'test '),
	(10, 'Aldrin Manay', 'acanlas495@gmail.com', '0939942847', 'asdwasdw', 'asdsdadsasadadsad');

-- Dumping structure for table realestatephp.feedback
CREATE TABLE IF NOT EXISTS `feedback` (
  `fid` int(50) NOT NULL AUTO_INCREMENT,
  `uid` int(50) NOT NULL,
  `fdescription` varchar(300) NOT NULL,
  `status` int(1) NOT NULL,
  `date` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`fid`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table realestatephp.feedback: ~1 rows (approximately)
REPLACE INTO `feedback` (`fid`, `uid`, `fdescription`, `status`, `date`) VALUES
	(9, 36, 'super lupit', 1, '2024-12-08 16:19:34');

-- Dumping structure for table realestatephp.property
CREATE TABLE IF NOT EXISTS `property` (
  `pid` int(50) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `pcontent` longtext NOT NULL,
  `type` varchar(100) NOT NULL,
  `bhk` varchar(50) NOT NULL,
  `stype` varchar(100) NOT NULL,
  `bedroom` int(50) NOT NULL,
  `bathroom` int(50) NOT NULL,
  `balcony` int(50) NOT NULL,
  `kitchen` int(50) NOT NULL,
  `hall` int(50) NOT NULL,
  `floor` varchar(50) NOT NULL,
  `size` int(50) NOT NULL,
  `price` int(50) NOT NULL,
  `location` varchar(200) NOT NULL,
  `city` varchar(100) NOT NULL,
  `state` varchar(100) NOT NULL,
  `feature` longtext NOT NULL,
  `pimage` varchar(300) NOT NULL,
  `pimage1` varchar(300) NOT NULL,
  `pimage2` varchar(300) NOT NULL,
  `pimage3` varchar(300) NOT NULL,
  `pimage4` varchar(300) NOT NULL,
  `uid` int(50) NOT NULL,
  `status` varchar(50) NOT NULL,
  `mapimage` varchar(300) NOT NULL,
  `topmapimage` varchar(300) NOT NULL,
  `groundmapimage` varchar(300) NOT NULL,
  `totalfloor` varchar(50) NOT NULL,
  `date` datetime NOT NULL DEFAULT current_timestamp(),
  `isFeatured` int(11) DEFAULT NULL,
  PRIMARY KEY (`pid`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table realestatephp.property: ~20 rows (approximately)
REPLACE INTO `property` (`pid`, `title`, `pcontent`, `type`, `bhk`, `stype`, `bedroom`, `bathroom`, `balcony`, `kitchen`, `hall`, `floor`, `size`, `price`, `location`, `city`, `state`, `feature`, `pimage`, `pimage1`, `pimage2`, `pimage3`, `pimage4`, `uid`, `status`, `mapimage`, `topmapimage`, `groundmapimage`, `totalfloor`, `date`, `isFeatured`) VALUES
	(35, 'Rent to own 2 Bedroom Condo for sale in St. Mark Residences McKinley Hill', '<p>ST. MARK RESIDENCES READY FOR OCCUPANCY | RENT TO OWN CONDO/APARTMENT</p>\r\n<p>-Along Venezia Drive, Mckinley Hill, Fort Bonifacio, Taguig City</p>\r\n<p>-Interconnected to Venice Grand Canal Mall</p>', 'apartment', '2 BHK', 'rent', 2, 3, 1, 1, 1, '1st Floor', 1104, 24000000, 'Upper McKinley Rd, 1634 Taguig City, Philippines McKinley Hill, Taguig', 'Taguig City', 'NCR', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'f8653556-d558-46e5-ac48-007290d2fd05.jpg', '27beb778-8aac-488c-a9ab-0ab4b263b5c6.jpg', '8ec4bdcd-5b6c-47fc-a8ea-606ac544af2d.jpg', '711effd8-c8d8-4f36-9445-fb48a3483dd2.jpg', '1e622431-5b26-4fdd-931a-16b489f981a1.jpg', 43, 'available', '3a1574fa-36b8-480e-9103-dfafe044508b.jpg', '', '', '14 Floor', '2024-12-15 02:44:48', 1),
	(36, 'For Sale 1 Bedroom Rent to Own Condo in St. Mark Residences McKinley Hill', '<p>ST. MARK RESIDENCES READY FOR OCCUPANCY | RENT TO OWN CONDO</p>\r\n<p>-Along Venezia Drive, Mckinley Hill, Fort Bonifacio, Taguig City</p>\r\n<p>-Interconnected to Venice Grand Canal Mall</p>', 'apartment', '2 BHK', 'rent', 1, 1, 1, 1, 1, '3rd Floor', 715, 15450000, 'Upper McKinley Rd, 1634 Taguig City, Philippines McKinley Hill, Taguig', 'Taguig City', 'NCR', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes0</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '294d631b-37cf-44a8-83b4-6fd658fb33df.jpg', '58e5ce12-db41-45ce-a44b-af4a13e41f2e.jpg', '1f9a088c-15de-468f-8a0f-583ca209a9b3.jpg', '815e48c3-4dd9-41dd-b73f-31151b839f8e.jpg', '7610dca4-418b-4d45-b704-f2412b09fa58.jpg', 43, 'available', 'a46d5434-a215-4b7f-ba3c-b0af237d600d.jpg', '', '', '14 Floor', '2024-12-15 03:05:09', 0),
	(37, '3 Bedrooms Brand New Townhouses in UPS5 Sucat Paranaque', '', 'apartment', '1 BHK', 'rent', 4, 5, 3, 1, 1, '2nd Floor', 1620, 9300000, 'San Isidro, Parañaque', ' Parañaque City', 'NCR', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '0a4ecb63-2a4c-4f50-9086-1dc71c8d0978.jpg', '44c95feb-49d6-4e30-88da-9971912edac8.jpg', 'b106175e-a95f-4e68-9314-a114347cc0e8.jpg', 'e815cd70-fc7a-4d2c-81ce-1443de4c8ca5.jpg', 'f9461d89-8d39-4eac-8018-e6468c8bd7c8.jpg', 43, 'available', 'dd6b1b44-aa8e-4935-92bf-d012120acf4f.jpg', '', '', '2 Floor', '2024-12-15 03:26:21', 0),
	(38, '5 Bedroom House and Lot For Sale in Basak, Lapu-Lapu City, Cebu, Philippines', '<p>Discover "Brookfalls" &ndash; a stunning waterfall-inspired home that combines elegance, luxury, and modern living in the tranquil Brookfield Subdivision, Basak, Lapu-Lapu City. Perfect for families seeking comfort or investors looking for a unique property in a peaceful community.</p>', 'house', '3 BHK', 'sale', 5, 4, 2, 1, 1, '3rd Floor', 5167, 19990000, 'Basak, Lapu-Lapu City, Central Visayas, Philippines Basak, Lapu-Lapu', 'Lapu-Lapu City', 'Cebu', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'd5712765-687d-4748-94aa-7257adf75942.jpg', 'a4a709d6-82d2-47b2-b11c-2cf5eba0dccd.jpg', 'b71c0d40-00e0-4759-b4aa-2ce8eaa271f9.jpg', '54d2701a-47fb-4d4c-8939-8fa67fd34131.jpg', '9da1cc84-6ce2-473a-ae4e-2c8fd4dc4bfc.jpg', 43, 'available', '', '', '', '3 Floor', '2024-12-15 03:36:14', 1),
	(39, 'HOUSE for sale M Residences , Mahogany place 3 Acacia Estates Taguig', '<p>House and Lot For Sale: Located in Mahogany Place 3, Acacia Estates, Taguig, this 600 sqm property with a 1,480 sqm floor area is 10-15 minutes from BGC and 15-20 minutes from the airport. It features a gym, pool, lanai, multiple bedrooms, an office, and a roof deck. Contact us for details!</p>', 'house', '1 BHK', 'sale', 6, 6, 2, 1, 1, '2nd Floor', 1480, 180000000, 'ACACIA ESTATES TAGUIG Ususan, Taguig', 'Taguig City', 'NCR', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'a5104e5f-30b3-4018-8590-ed61de601dc4.jpg', '696ccfb9-844d-4f53-a213-809b1b86ef88.jpg', '7a43f9c7-685b-4016-a024-7ebb4ab9544f.jpg', '5be441fd-28d3-4d88-b7f2-76fdd60c5dfb.jpg', '0bddf4a1-402d-444d-9b15-0bec0acfc1be.jpg', 44, 'available', '', '', '', '2 Floor', '2024-12-15 03:54:13', 0),
	(40, 'FOR SALE: Sta. Rosa Heights, Sta. Rosa-Tagaytay Expressway. 2 sty 2 BR garde', '<p>Claim Your Hilltop Home Now! Live in Sta. Rosa Heights, a peaceful, flood-free gated community with fresh air, wide roads, nearby schools, and easy access to beaches, golf courses, and malls. Enjoy 24/7 security and reliable utilities. Move in today!</p>', 'house', '1 BHK', 'sale', 2, 1, 0, 1, 1, '1st Floor', 646, 4800000, 'Sta Rosa Heights, along Sta Rosa-Tagaytay Expressway, Silang, Cavite Puting Kahoy, Silang', 'Cavite City', '	Calabarzon', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '175cbfef-9231-4724-92ec-e2f9f386bd80.jpg', '5c091e3b-f769-483f-b3b2-6d1c5c3b55e5.jpg', '6ded1bcf-fba5-4590-a575-fc73f60756a9.jpg', 'a2ef99dd-9405-435c-90c7-3cb885cc2bd6.jpg', 'fb1cc243-5c69-4c3d-af80-cf841578dd08.jpg', 44, 'available', '', '', '', '1 Floor', '2024-12-15 04:03:19', 0),
	(41, '4 BR with T&B Newly Constructed Near NAIA House & Lot for Sale in Las Piñas City', '<p>An Amazing Brand New Duplex House and Lot for Sale in Las Pi&ntilde;as City</p>', 'house', '1 BHK', 'sale', 4, 4, 0, 1, 1, '2nd Floor', 217, 15000000, 'Talon Dos, Las Piñas, National Capital Region, Philippines Talon Dos, Las Piñas', 'Las Piñas City', 'NCR', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'c5a19e23-fe42-4c14-a456-0470f14da3ca.jpg', 'bcbf5e7b-ef1c-47c1-9a16-8e23ac1a991f.jpg', 'a4330423-e659-49f8-ac00-0743e29d155d.jpg', '5918752d-9c7b-492c-b272-2d51362e5036.jpg', '6c5bd012-a21e-4a4a-876d-3b9185904a84.jpg', 44, 'available', '', '', '', '2 Floor', '2024-12-15 04:09:00', 0),
	(42, 'PARKRIDGE ESTATE HOUSE ANTIPOLO', '<p><strong class="html-b xdj266r x11i5rnm xat24cr x1mh8g0r xexx8yu x4uap5 x18d9i69 xkhd6sd x1hl2dhg x16tdsg8 x1vvkbs">*Claim Your Hilltop Home Now!*</strong></p>\r\n<p>Enjoy peaceful, flood-free living in Sta. Rosa Heights, an 80-hectare gated community with fresh mountain air, wide roads, and nearby schools. Conveniently close to Batangas beaches, golf courses, malls, and spas, it offers 24/7 security, reliable utilities, and a healthy, tranquil lifestyle. Move in today!</p>', 'villa', '2 BHK', 'sale', 5, 4, 2, 1, 1, '2nd Floor', 2000, 135000000, 'Santa Cruz, Antipolo', 'Antipolo City', 'Rizal', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'e571f222-1f0c-4a04-a28f-314a391d1b5a.jpg', 'e71ee845-fc3f-4615-8fb3-e39cda4c56d1.jpg', 'dc7c7a2e-5918-4640-ad9f-9439fa666dc3.jpg', '0105f9c9-0669-4338-b21d-a37d833c420e.jpg', '20fa5285-df6f-419a-a82e-7afa1eba75b5.jpg', 44, 'available', '', '', '', '2 Floor', '2024-12-15 04:13:33', 1),
	(43, 'Luxury 5-bedroom House & Lot For Sale w/ Pool, Jardin Busay, Cebu City', '<p>Indulge in Unmatched Luxury - Your Exquisite Overlooking House and Lot in Cebu City Awaits!</p>', 'villa', '1 BHK', 'sale', 5, 9, 2, 1, 1, '2nd Floor', 1458, 120000000, 'Busay, Cebu', 'Cebu City', 'Cebu', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'c1a722db-5e0d-4043-93be-98ee0344518d.jpg', 'a6acc4ac-935b-434d-9eea-44f885bd98ef.jpg', '87718bab-e40b-423d-8c7f-82daa2726b39.jpg', '340f82b5-4eea-4d6b-bbaf-8b8eb020867f.jpg', '5e2bb401-0866-41aa-bae8-c54a07af6737.jpg', 45, 'available', '', '', '', '2 Floor', '2024-12-15 04:24:18', 0),
	(44, '3-Bedroom Luxury House and Lot For Sale in Talamban, Cebu City, Philippines', '<p>This spacious 750 sqm home on a 561 sqm lot offers 3 bedrooms, a modern kitchen, multiple living areas, and a 3-car garage. Now priced at P77.5M (down from P85M), it comes fully furnished with a swimming pool, outdoor gym, and additional amenities. Don&rsquo;t miss out&mdash;make an offer today!</p>', 'villa', '1 BHK', 'sale', 3, 3, 1, 1, 2, '2nd Floor', 750, 77480000, 'Nasipit, Cebu City, Central Visayas, Philippines Talamban, Cebu', 'Cebu City', 'Cebu', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '97f2dff6-f1c1-4150-963d-5a7805bb1a69.jpg', 'ce415fe8-2cc2-4a0a-a3d9-a0b8729fa9ad.jpg', '78df7d0e-e2fb-4793-8747-8550aad1d010.jpg', '805e968c-46dd-4a83-9a74-e89239359d77.jpg', 'bf4f2161-a09f-4e7b-8ef4-73e449d8b55a.jpg', 45, 'available', '', '', '', '2 Floor', '2024-12-15 04:29:38', 0),
	(45, 'Rush Sale! Apartment Building for Sale in Quezon City', '<p>If you want to know the fair market value of your property, we do appraisal services, valuation, and consultancy within 5-7 days.</p>', 'apartment', '1 BHK', 'rent', 7, 3, 1, 1, 1, '2nd Floor', 800, 25000000, 'Tandang Sora, Quezon City', ' Quezon City', 'NCR', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'e5c8eb50-8fec-4a5d-ab0f-b759766632e3.jpg', '0b46baab-9c40-404f-a34f-c8590ca3fe2c.jpg', '0b46baab-9c40-404f-a34f-c8590ca3fe2c (1).jpg', '3585fbb1-f610-4aca-b186-eb0218845ff2.jpg', '986e9028-d287-4dfd-bd87-805e4a03b013.jpg', 45, 'available', '', '', '', '2 Floor', '2024-12-15 04:47:30', 0),
	(46, 'OPERATIONAL APARTMENT FOR SALE in LAPU-LAPU CITY, CEBU, PHILIPPINES', '<p>COMMUNITY FACILITIES AND UTILITIES: Electric power,water supply,and telecommunication facilities are available at the site and its neighborhood.Buses,jeepneys,and taxis are the major modes of public transportation that connects from the location of the subject property to different parts of Lapu-Lapu and its neighboring cities and municipalities. Community facilities and utilities are maintained by the city government and chartered private entities.</p>', 'apartment', '1 BHK', 'rent', 10, 10, 1, 1, 1, '1st Floor', 1000, 50000000, 'Pajac, Lapu-Lapu', 'Lapu-Lapu City', 'Cebu', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'c4d3a188-b443-4e7c-952c-650ef1edbca3.jpg', 'a198a30c-e17b-4317-a1f7-750baba10cac.jpg', 'cc06cee9-660c-4f44-b60f-fb5864058a7f.jpg', 'e798197c-7265-464c-b0aa-8dd2b68a2a1c.jpg', '39852f58-9e78-43ea-abda-6b5e1ecee87b.jpg', 46, 'available', '', '', '', '1 Floor', '2024-12-15 04:54:13', 0),
	(47, 'For Sale Brand New 4 Bedrooms Residential House in Greenheights Village', '<p>This brand-new 4-bedroom, 3-bathroom residential house in Greenheights Village, Para&ntilde;aque offers a spacious 300 sqm lot and 350 sqm of floor area. Featuring a master&rsquo;s bedroom en-suite, modular kitchen cabinets, split-type air conditioners, and a garden, this home provides both comfort and style. It also includes 2 parking slots and is priced at ₱29,500,000. Payment options are available, with an estimated monthly amortization starting at ₱211,404 for 15 years.</p>', 'house', '1 BHK', 'sale', 4, 3, 1, 1, 2, '2nd Floor', 350, 29500000, 'Parañaque', 'Parañaque', 'NCR', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '038b20b3-a3de-471d-aff0-023c712a44af.jpg', '019381a7-f862-4946-8767-69d6324e63cc.jpg', 'a50a7d43-e0b8-4336-9f71-cc223b0a1b75.jpg', 'a936bc4f-4215-4ba9-93dc-29ec10f76d77.jpg', 'ec790a78-4941-4cba-8ffc-788376af9aa7.jpg', 46, 'available', '', '', '', '2 Floor', '2024-12-15 04:57:44', 0),
	(48, 'House and Lot For Sale in Ayala Alabang Village, Muntinlupa City', '<p>Brand New House and Lot For Sale in Ayala Alabang Village, Muntinlupa City The property a Bungalow house is perfect for Senior&rsquo;s citizens or newlywed. This house is more manageable not too big and easy to maintain. But your still in one in a Private Luxurious Village in the South of Metro Manila. It comes with a Den or Office, a swimming pool, a garden, and a separate maids &amp; driver&rsquo;s room.</p>', 'house', '1 BHK', 'sale', 3, 2, 0, 1, 1, '1st Floor', 425, 135000000, 'Ayala Alabang, Muntinlupa', ' Muntinlupa City', 'NCR', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'b2bb41c4-4e31-4d13-a2c7-5167b5268280.jpg', '4e99b60e-f09a-4f4f-accd-ddca68387688.jpg', '6d3212f3-1903-40f1-b243-c5c8b0dfad3d.jpg', '172e9255-fd38-4706-85ea-1f2eee68300e.jpg', '487a55b5-d3c0-437e-a0f5-40d2de34ef99.jpg', 46, 'available', '', '', '', '1 Floor', '2024-12-15 05:01:55', 0),
	(49, '5 Door Apartment for Sale in Angeles City, Pampanaga near Marquee mall', '<p>For sale: 5-unit Residential Property Lot Size: 300 sqm Floor Area: 410 sqm Price: ₱13.5M Each unit features: 2 Bedrooms 1 Bathroom (on the 2nd floor) Living room, dining, and kitchen area Powder room Laundry area Veranda Parking space The property includes: 4 units at 80 sqm 1 unit at 90 sqm Unfurnished. Perfect for investment or family living.</p>', 'apartment', '1 BHK', 'rent', 10, 5, 5, 1, 1, '2nd Floor', 410, 13500000, 'Amsic, Angeles', 'pampanga city', 'San Fernando', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '54ae2c2e-c74e-4db4-92ab-3a48a3a1e449.jpg', '1150f46a-8a04-4961-8d3d-6b1dc9456cfc.jpg', '76015724-2e43-406b-8f3c-3ce6a05c2a55.jpg', '80732040-2066-47d6-a97b-0e6183e1393a.jpg', 'eaaac112-3cf5-4567-9739-82519784233e.jpg', 48, 'available', '', '', '', '2 Floor', '2024-12-15 05:09:13', 0),
	(50, '3 Storey Modern House & Lot for sale in Ayala Westgrove Heights w/ 360 views', '<p>FOR SALE Ayala Westgrove Heights Modern House and Lot w/ 360 views</p>', 'villa', '3 BHK', 'sale', 5, 6, 1, 1, 3, '3rd Floor', 650, 120000000, 'Ayala Westgrove Heights Inchican 4118 Silang Cavite Puting Kahoy, Silang', 'Cavite ', 'CALABARZON', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '607c3bf5-87d2-4f63-a2dd-7d8887ba2523.jpg', '84c11ab7-eb4c-46ce-95c0-452ffbd5ca4b.jpg', '4363eaba-fabf-45fd-9ca2-ea865ebfe613.jpg', '42437bc9-6734-4477-bc1c-cabf7aa4e186.jpg', 'b79dddab-44f7-4bd7-8299-cd08a1ad6ee1.jpg', 48, 'available', '', '', '', '3 Floor', '2024-12-15 05:14:10', 0),
	(51, '5 Bedroom Overlooking Brand New House and Lot For Sale in Guadalupe, Cebu City', '<p>5 BEDROOM LUXURY and OVERLOOKING SINGLE DETACHED HOUSE IN CEBU CITY MONTERRAZAS PRIME CEBU SPECIAL UNIT FOR SALE Monterrazas de Cebu, Guadalupe, Cebu city</p>', 'villa', '1 BHK', 'sale', 5, 5, 1, 1, 1, '2nd Floor', 812, 189990000, 'Guadalupe, Cebu City, Central Visayas, Philippines Guadalupe, Cebu', 'Cebu City', 'Cebu', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '4c598bf7-ada5-4f41-8bc8-82649e0ac0c4.jpg', '0e38ad5e-5865-44db-8d2c-9d7018616d32.jpg', '60d26f29-e5fc-4857-8663-464a4f9c1ed3.jpg', 'b53743de-2b34-49c1-be66-6482cc8351ac.jpg', 'f35a98b7-5bd9-4081-8e91-ac1e0724d1fb.jpg', 48, 'available', '87a42674-537f-4da5-bb9d-1125a21c7470.jpg', '', '', '2 Floor', '2024-12-15 05:19:23', 0),
	(52, 'For Sale: 4BR House and Lot in BF Homes Paranaque', '<p>Other features and inclusions: - Family area w/ Balcony - Landscape garden - Powder room - Spacious Modern Kitchen w/ Appliances - Dirty Kitchen - Spacious Service Kitchen - Maid&rsquo;s Room w/ T&amp;B - Driver&rsquo;s Room - Laundry Area</p>', 'house', '1 BHK', 'sale', 4, 4, 1, 1, 2, '2nd Floor', 380, 36500000, 'B.F Homes, Paranaque City B.F. Homes, Parañaque', 'Parañaque City', 'NCR', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'cdf29b0a-06bc-4251-8bf4-5ae87d70df11.jpg', '8c09439a-3801-40e3-b11c-c25af805ad0d.jpg', 'd9722f25-e198-4e03-b588-0aaf5d8e4908.jpg', 'de1a4181-0ec1-4ba3-a0e0-559eea7d1405.jpg', 'e04ab331-863d-4e84-b2ed-b2c6da2322be.jpg', 47, 'available', '', '', '', '2 Floor', '2024-12-15 05:23:46', 0),
	(53, '3 BR Single Attached Unit for Sale at Eastridge Golf Villas in Binangonan, Rizal (Ruby)', '', 'house', '1 BHK', 'sale', 3, 2, 1, 1, 1, '2nd Floor', 0, 5261000, 'Palangoy, Binangonan', 'Binangonan City', 'Rizal', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'd84b8225-290f-4af3-b4fb-20e99f46a51d.jpg', '01fc0eeb-17af-43e5-a233-6c7526fbdd50.jpg', '4a0e41c7-98ab-4724-9fd1-5b57279e268a.jpg', '21bb5a21-84bb-4116-bbbf-52c3fc70a30a.jpg', '904fe21a-fd1c-437c-93db-bba407ed0536.jpg', 47, 'available', 'ee31e71c-0465-4122-98e5-2e39302e1777.jpg', '', '', '2 Floor', '2024-12-15 05:27:44', 1),
	(54, '4 Bedroom Townhouse Unit for Sale at Tanza Garden Enclave in Tanza, Cavite', '<p>Tanza Garden Enclave is a serene residential community located in the heart of Tanza, Cavite. This master-planned development offers modern house-and-lot units, providing a perfect blend of comfort, style, and functionality. Designed for families and individuals looking for a peaceful and secure living environment, Tanza Garden Enclave is the ideal place to create cherished memories and build a future.</p>', 'house', '1 BHK', 'sale', 4, 2, 1, 1, 1, '1st Floor', 0, 3988000, 'Punta I, Tanza', 'Cavite City', '	Calabarzon', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Property Age : </span>10 Years</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Swiming Pool : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Parking : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Type : </span>Apartment</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Security : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Dining Capacity : </span>10 People</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Church/Temple : </span>No</li>\r\n</ul>\r\n</div>\r\n<div class="col-md-4">\r\n<ul>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">3rd Party : </span>No</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Elevator : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">CCTV : </span>Yes</li>\r\n<li class="mb-3"><span class="text-secondary font-weight-bold">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'ed9b9d4f-186a-44c8-9f0b-c558b3869c90.jpg', '7363b3b1-d375-49fc-aff6-325fe1397581.jpg', 'edd289ab-3361-48e9-8829-cc6bd2604ae1.jpg', '642e4bfe-0802-4dae-965e-04479ce0ad47.jpg', '5b7e06ee-d16b-4bc6-80d9-12196282d46f.jpg', 47, 'available', '', '', '', '1 Floor', '2024-12-15 05:30:44', 1);

-- Dumping structure for table realestatephp.state
CREATE TABLE IF NOT EXISTS `state` (
  `sid` int(50) NOT NULL AUTO_INCREMENT,
  `sname` varchar(100) NOT NULL,
  PRIMARY KEY (`sid`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table realestatephp.state: ~1 rows (approximately)
REPLACE INTO `state` (`sid`, `sname`) VALUES
	(23, 'Philippines');

-- Dumping structure for table realestatephp.user
CREATE TABLE IF NOT EXISTS `user` (
  `uid` int(50) NOT NULL AUTO_INCREMENT,
  `uname` varchar(100) NOT NULL,
  `uemail` varchar(100) NOT NULL,
  `uphone` varchar(20) NOT NULL,
  `upass` varchar(50) NOT NULL,
  `utype` varchar(50) NOT NULL,
  `uimage` varchar(300) NOT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table realestatephp.user: ~8 rows (approximately)
REPLACE INTO `user` (`uid`, `uname`, `uemail`, `uphone`, `upass`, `utype`, `uimage`) VALUES
	(36, 'testuser', 'testuser@gmail.com', 'test', 'a94a8fe5ccb19ba61c4c0873d391e987982fbbd3', 'user', 'profile_36.jpg'),
	(43, 'Aldrin Manay', 'aldrin@gmail.com', '0909090909', '8746015474cd01110181ed51735247560fd08de4', 'agent', 'a3f67216-8882-4c16-a40d-3e19207c7887 (1).jpg'),
	(44, 'Kent Martin Perez', 'kent@gmail.com', '0909090909', '096b20d99b20901237894f458944cd17c570d85e', 'agent', 'a3f67216-8882-4c16-a40d-3e19207c7887 (1).jpg'),
	(45, 'Erika Jane Licudan', 'Erika@gmail.com', '0909090909', 'a6f0da1b1ba6aecebb2c15af8771766d21fc471d', 'agent', 'a3f67216-8882-4c16-a40d-3e19207c7887 (1).jpg'),
	(46, 'Jersey Monterde', 'jersey@gmail.com', '0909090909', '5a5d7a49980fd29f234a4feede52d85488445d38', 'agent', 'a3f67216-8882-4c16-a40d-3e19207c7887 (1).jpg'),
	(47, 'Maria Michaela Ng', 'maria@gmail.com', '0909090909', 'e21fc56c1a272b630e0d1439079d0598cf8b8329', 'agent', 'a3f67216-8882-4c16-a40d-3e19207c7887 (1).jpg'),
	(48, 'Cedric Moaje', 'cedric@gmail.com', '0909090909', '240633aa59d25638de9800ef43a88ad2e208d24d', 'agent', 'a3f67216-8882-4c16-a40d-3e19207c7887 (1).jpg'),
	(49, 'Aldrin Manay', 'acanlas495@gmail.com', '0909090909', '8746015474cd01110181ed51735247560fd08de4', 'user', 'edd289ab-3361-48e9-8829-cc6bd2604ae1.jpg');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
